//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class code
    {
        public int id { get; set; }
        public Nullable<int> group_id { get; set; }
        public Nullable<int> unit_id { get; set; }
        public Nullable<int> company_id { get; set; }
        public Nullable<int> item_information_id { get; set; }
        public Nullable<int> sale_order_id { get; set; }
        public Nullable<int> purchase_order_id { get; set; }
        public Nullable<int> sale_id { get; set; }
        public Nullable<int> purchase_id { get; set; }
        public Nullable<int> chalan_id { get; set; }
        public Nullable<int> material_cent_id { get; set; }
        public Nullable<int> article_no { get; set; }
        public Nullable<decimal> barcode { get; set; }
        public Nullable<int> state_id { get; set; }
    }
}
