//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_information
    {
        public int id { get; set; }
        public string item_id { get; set; }
        public string item_barcode { get; set; }
        public string item_article_no { get; set; }
        public string item_name { get; set; }
        public string item_print_name { get; set; }
        public string item_group_name { get; set; }
        public string item_company_name { get; set; }
        public string item_unit_name { get; set; }
        public Nullable<decimal> item_CGST { get; set; }
        public Nullable<decimal> item_SGST { get; set; }
        public Nullable<decimal> item_IGST { get; set; }
        public Nullable<decimal> item_MRP { get; set; }
        public Nullable<decimal> item_purchase_price { get; set; }
        public Nullable<decimal> item_sale_price { get; set; }
        public Nullable<decimal> item_previous_stock { get; set; }
        public Nullable<decimal> item_stock_amount { get; set; }
        public string item_description { get; set; }
        public Nullable<decimal> item_maxlevel_qty { get; set; }
        public Nullable<decimal> item_minlevel_qty { get; set; }
        public byte[] img { get; set; }
        public Nullable<bool> item_block { get; set; }
        public Nullable<bool> item_deleted { get; set; }
    }
}
