//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ebmsEntities : DbContext
    {
        public ebmsEntities()
            : base("name=ebmsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<code> codes { get; set; }
        public virtual DbSet<item_company> item_company { get; set; }
        public virtual DbSet<item_group> item_group { get; set; }
        public virtual DbSet<item_unit> item_unit { get; set; }
        public virtual DbSet<item_material_centre> item_material_centre { get; set; }
        public virtual DbSet<state_list> state_list { get; set; }
        public virtual DbSet<item_information> item_information { get; set; }
        public virtual DbSet<userlogin> userlogins { get; set; }
        public virtual DbSet<Item_tax> Item_tax { get; set; }
    }
}
